'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SCOM2012MaintenanceMode.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _13___Help() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_13___Help", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Add() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Add", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Arrow_Dn() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Arrow_Dn", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Arrow_Up() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Arrow_Up", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___CLU() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___CLU", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___COM() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___COM", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Connecting() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Connecting", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Help___Closed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Help___Closed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Help___Open() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Help___Open", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16___Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Remove() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Remove", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Blank() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Blank", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Failed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Failed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Maintenance() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Maintenance", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___NothingToDo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___NothingToDo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Pass() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Pass", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Scanning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Scanning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Scan___Warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Scan___Warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Select_All() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Select_All", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Select_None() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Select_None", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Selection_Invert() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Selection_Invert", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _16___Server() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16___Server", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property C() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("C", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkbox___on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbox___on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property E() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("E", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0000() As String
            Get
                Return ResourceManager.GetString("help0000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0100() As String
            Get
                Return ResourceManager.GetString("help0100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0101() As String
            Get
                Return ResourceManager.GetString("help0101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0102() As String
            Get
                Return ResourceManager.GetString("help0102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0103() As String
            Get
                Return ResourceManager.GetString("help0103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0104() As String
            Get
                Return ResourceManager.GetString("help0104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0105() As String
            Get
                Return ResourceManager.GetString("help0105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0151() As String
            Get
                Return ResourceManager.GetString("help0151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0200() As String
            Get
                Return ResourceManager.GetString("help0200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0201() As String
            Get
                Return ResourceManager.GetString("help0201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0300() As String
            Get
                Return ResourceManager.GetString("help0300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0301() As String
            Get
                Return ResourceManager.GetString("help0301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0303() As String
            Get
                Return ResourceManager.GetString("help0303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0400() As String
            Get
                Return ResourceManager.GetString("help0400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0401() As String
            Get
                Return ResourceManager.GetString("help0401", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0402() As String
            Get
                Return ResourceManager.GetString("help0402", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0500() As String
            Get
                Return ResourceManager.GetString("help0500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0501() As String
            Get
                Return ResourceManager.GetString("help0501", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos;
        '''&apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        '''&lt;head&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-16&quot;&gt;
        '''&lt;META NAME=&quot;lcid&quot; CONTENT=&quot;1033&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;stylesheet.css&quot;&gt;
        '''&lt;!-- STYLESHEET --&gt;
        '''&lt;/head&gt;&lt;body class=&quot;clientViewer&quot;&gt;&lt;div class=&quot;bc&quot;&gt;&lt;span&gt;
        '''&amp;nbsp;&lt;!-- BREADCRUMB --&gt;
        '''&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;pTitle&quot;&gt;&lt;span class=&quot;pATitl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help0502() As String
            Get
                Return ResourceManager.GetString("help0502", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property M() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("M", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MainIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MainIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property N() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("N", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property O() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("O", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to body
        '''{
        '''	padding: 0;
        '''	margin: 0;
        '''	background-color: #ffffff;
        '''	line-height: normal;
        '''	font-family: Segoe UI, Arial, Verdana;
        '''	font-size: 75%;
        '''	min-width: 385px;
        '''}
        '''
        '''.code
        '''{
        '''	font-family: Courier New!important;
        '''}
        '''
        '''.label
        '''{
        '''	font-family: Courier New!important;
        '''	font-weight: bold;
        '''	color: #9090ff;
        '''}
        '''
        '''.black
        '''{
        '''	color: #000000;
        '''}
        '''
        '''.gray
        '''{
        '''	color: #909090;
        '''}
        '''
        '''img
        '''{
        '''	vertical-align:middle;
        '''}
        '''
        '''th
        '''{
        '''	text-align: left;
        '''	padding: 0 10px 2px 10px;
        '''	border-bottom-style: solid;
        '''	bor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property stylesheet() As String
            Get
                Return ResourceManager.GetString("stylesheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property W() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("W", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
